edition = "2021"

format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
hard_tabs = true
hex_literal_case = "Upper"
imports_granulatiry = "Crate"
reorder_impl_items = true
reorder_modules = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
